import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin.user';
import { globals } from '../modules/globals/globals';

export const settingsConfig: SettingSchemaDesc[] = [
    {
        key: 'promoAwesomeStyler',
        title: '',
        description: globals.promoAwesomeStylerMsg,
        type: 'boolean',
        default: false,
    },
    {
        key: 'appUIHeading',
        title: 'App UI tuning',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'featureWideSearchEnabled',
        title: '',
        description: 'Enable wide ("browser-like") search bar and search popup?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'featureCompactSidebarMenuEnabled',
        title: '',
        description: 'Compact menu (horizontal, no labels) on left sidebar?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'featureCalendarEnabled',
        title: '',
        description: 'Enable "Calendar" page menu sidebar item?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'featureHomeButtonEnabled',
        title: '',
        description: 'Show "Home" button on header?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'featureSidebarNewPageEnabled',
        title: '',
        description: 'Show "New Page" button on bottom of left sidebar?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'featureSidebarPageIconEnabled',
        title: '',
        description: 'Show default page icons on left sidebar favs/recent?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'featureNewBlockBulletEnabled',
        title: '',
        description: 'Always show add block bullet on page bottom?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'contentHeading',
        title: 'Content',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'featureTasksEnabled',
        title: '',
        description: 'Enable tasks status and priority restyling?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'featureColumnsEnabled',
        title: '',
        description: 'Enable columns: "#.kanban" & "#.grid" tags?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'featureQuoteEnabled',
        title: '',
        description: 'Enable blockquote style for "#quote" tag?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'contentFlashcard',
        title: '',
        description: 'Flashcard style for "#card" tag?',
        type: 'enum',
        enumPicker: 'radio',
        enumChoices: ['Default', 'Awesome', 'Flat'],
        default: 'Awesome',
    },
    {
        key: 'featureHeadersLabelsEnabled',
        title: '',
        description: 'Show headers (h1-h5) labels?',
        type: 'boolean',
        default: true,
    },
    {
        key: 'contentMermaid',
        title: '',
        description: 'Apply theme styles to Mermaid diagrams? (use plugin https://github.com/xyhp915/logseq-fenced-code-plus)',
        type: 'boolean',
        default: true,
    },
    {
        key: 'otherHeading',
        title: 'Other',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'featureUpdaterEnabled',
        title: '',
        description: 'Enable new version notifier on app load?',
        type: 'boolean',
        default: true,
    },
];